pipeline {
    agent {
        label 'ubuntu-node'
    }
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f jenkins/java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Create Tomcat Image') {
            agent {
                label 'ubuntu-node'
            }
            steps {
                copyArtifacts filter: '**/*.war', fingerprintArtifacts: true, projectName: env.JOB_NAME, selector: specific(env.BUILD_NUMBER)
                echo "Building docker image"
                sh '''
                original_pwd=$(pwd -P)
                cd jenkins/java-tomcat-sample
                docker build -t localtomcatimg:$BUILD_NUMBER .
                cd $original_pwd
                sh '''
            }
        }
        stage('Deploy to Stagging Env') {
            agent {
                label 'ubuntu-node'
            }
            steps {
                echo "Renaming java-tomcat-maven-example.war to ROOT.war..."
                sh '''
                 # Ensure the .war file exists in the current directory
                if [ ! -f java-tomcat-maven-example.war ]; then
                  echo "ERROR: java-tomcat-maven-example.war not found!"
                exit 1
                fi
                mv java-tomcat-maven-example.war ROOT.war

                # Confirm the rename was successful
               if [ ! -f ROOT.war ]; then
                echo "ERROR: Failed to rename java-tomcat-maven-example.war to ROOT.war"
               exit 1
               fi
              '''
             echo "Running app on Production environment..."
             sh '''

                docker stop tomcatInstanceStaging || true
                docker rm tomcatInstanceStaging || true
                docker run -itd --name tomcatInstanceStaging -p 8082:8080 localtomcatimg:$BUILD_NUMBER
                sh '''
            }
        }
        stage('Deploy Production Environment') {
            agent {
                label 'ubuntu-node'
            }
            steps {
                timeout(time:1, unit:'DAYS'){
                input message:'Approve PRODUCTION Deployment?'
                }
                echo "Running app on Prod env"
                sh '''
              
                docker stop tomcatInstanceProd || true
                docker rm tomcatInstanceProd || true
                docker run -itd --name tomcatInstanceProd -p 8083:8080 localtomcatimg:$BUILD_NUMBER
                '''
            }
        }
    }
  




}
